image: "ruby:2.5"

services:
  - postgres:latest

.cache_bundler: &cache_bundler
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - cache/bundle/

.setup_test_env: &setup_test_env
  before_script:
    # Check installation
    - ruby -v
    - which ruby

    # Install dependencies
    - apt-get update -qq && apt-get install -y -qq nodejs cmake
    
    # Project Setup
    - gem install bundler --no-ri --no-rdoc
    - bundle check || bundle install --path=cache/bundler --jobs $(nproc) "${FLAGS[@]}"
    - cp config/database.yml.gitlab config/database.yml
    - bundle exec rails db:create RAILS_ENV=test 
    - bundle exec rails db:schema:load RAILS_ENV=test

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1

stages:
  - test
  - lint
  - deploy

test:
  stage: test
  <<: *cache_bundler
  <<: *setup_test_env
  script:
    - RAILS_ENV=test bundle exec rspec

Pronto:
  stage: lint
  <<: *cache_bundler
  <<: *setup_test_env
  allow_failure: true
  script:
    - bundle exec pronto run -c=origin/master --exit-code

Deploy Staging:
  stage: deploy
  retry: 2
  environment:
    name: staging
    url: https://liuchores-staging.herokuapp.com
  script:
    - ./bin/setup_heroku
    - dpl --provider=heroku --app=liuchores-staging --api-key=$HEROKU_API_KEY
    - heroku run rake db:migrate --exit-code --app liuchores-staging
  only:
    - master

Deploy Production:
  stage: deploy
  retry: 2
  environment:
    name: production
    url: https://liuchores-production.herokuapp.com
  script:
    - ./bin/setup_heroku
    - dpl --provider=heroku --app=liuchores-production --api-key=$HEROKU_API_KEY
    - heroku run rake db:migrate --exit-code --app liuchores-staging
  only:
    - tags
